//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesViews {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ponant.Medical.Shore.Resources.Views.Upload.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allowed file formats: PDF, JPG, JPEG, PNG, GIF, TIF, TIFF, BMP, XPS.
        /// </summary>
        public static string AllowedFormats {
            get {
                return ResourceManager.GetString("AllowedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        public static string BtnSend {
            get {
                return ResourceManager.GetString("BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dear.
        /// </summary>
        public static string CivilityTitle {
            get {
                return ResourceManager.GetString("CivilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must complete at least one related document.
        /// </summary>
        public static string ErrorRelatedDocuments {
            get {
                return ResourceManager.GetString("ErrorRelatedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum file size: 8 MB.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To complete your registration, please fill out the form below..
        /// </summary>
        public static string FillForm {
            get {
                return ResourceManager.GetString("FillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your booking reservation has been made with.
        /// </summary>
        public static string MadeWith {
            get {
                return ResourceManager.GetString("MadeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medical Survey.
        /// </summary>
        public static string MedicalSurvey {
            get {
                return ResourceManager.GetString("MedicalSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The MedicalSurvey field is required.
        /// </summary>
        public static string MedicalSurveyFileRequired {
            get {
                return ResourceManager.GetString("MedicalSurveyFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A medical survey has already been sent. do you want to send another one?.
        /// </summary>
        public static string QmAlreadySent {
            get {
                return ResourceManager.GetString("QmAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string radioBtnCancel {
            get {
                return ResourceManager.GetString("radioBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string radioBtnValid {
            get {
                return ResourceManager.GetString("radioBtnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Related Documents.
        /// </summary>
        public static string RelatedDocuments {
            get {
                return ResourceManager.GetString("RelatedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à * Required fields.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In accordance with the &quot;General Data Protection Regulation&quot; or &quot;GDPR&quot;, the information collected in the form is recorded in a computerized file by PONANT for the strict needs of your file. The legal basis for the processing is your consent.
        ///The data collected will be communicated to the controller of the processing, PONANT, as mentioned on this document.
        ///The data will be kept for the conservation period necessary for the purpose of the processing and the needs of your cruise.
        ///You may access your data, re [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string RGPD {
            get {
                return ResourceManager.GetString("RGPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We will have the pleasure of welcoming you very soon aboard our ship.
        /// </summary>
        public static string ShipPresentation {
            get {
                return ResourceManager.GetString("ShipPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The medical survey should NOT completed or submitted until maximum 3 months before your departure date..
        /// </summary>
        public static string WarningDeparture {
            get {
                return ResourceManager.GetString("WarningDeparture", resourceCulture);
            }
        }
    }
}
