IF NOT EXISTs(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Language' AND COLUMN_NAME = 'IndividualAutomaticResponse')
BEGIN
	ALTER TABLE Language ADD IndividualAutomaticResponse VARCHAR(64);
END
GO

IF NOT EXISTs(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Language' AND COLUMN_NAME = 'GroupAutomaticResponse')
BEGIN
	ALTER TABLE Language ADD GroupAutomaticResponse VARCHAR(64);
END
GO