//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Board.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cruise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cruise()
        {
            this.Passenger = new HashSet<Passenger>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int PassengersNumber { get; set; }
        public int SurveyNumberAvailable { get; set; }
        public int SurveyNumberSent { get; set; }
        public int SurveyNumberDownloaded { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Editor { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public System.DateTime SailingDate { get; set; }
        public int SailingLengthDays { get; set; }
        public int SurveyNumberDoneBoard { get; set; }
        public int SurveyNumberDoneShore { get; set; }
        public bool IsExtract { get; set; }
        public int IdShip { get; set; }
        public int SurveyNumberNotAvailable { get; set; }
        public int SurveyNumberReceive { get; set; }
        public int SurveyNumberValidate { get; set; }
        public int SurveyNumberWaiting { get; set; }
        public int SurveyNumberRefused { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> IdShipAssigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passenger { get; set; }
        public virtual Lov Lov { get; set; }
    }
}
