//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingActivity = new HashSet<BookingActivity>();
            this.BookingCruisePassenger = new HashSet<BookingCruisePassenger>();
        }
    
        public int Id { get; set; }
        public int IdLanguage { get; set; }
        public int IdAgency { get; set; }
        public int Number { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Editor { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public int IdOffice { get; set; }
        public string GroupName { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<int> IdSurveyLanguage { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Lov LovLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingActivity> BookingActivity { get; set; }
        public virtual Lov LovOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCruisePassenger> BookingCruisePassenger { get; set; }
    }
}
