//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseCriterion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CruiseCriterion()
        {
            this.CruiseCriterionDestination = new HashSet<CruiseCriterionDestination>();
            this.CruiseCriterionShip = new HashSet<CruiseCriterionShip>();
        }
    
        public int Id { get; set; }
        public int IdSurvey { get; set; }
        public int IdCruiseType { get; set; }
        public int Order { get; set; }
        public string Cruise { get; set; }
        public Nullable<int> Length { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Editor { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string Activity { get; set; }
    
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruiseCriterionDestination> CruiseCriterionDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruiseCriterionShip> CruiseCriterionShip { get; set; }
        public virtual Lov LovCruiseType { get; set; }
    }
}
