//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cruise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cruise()
        {
            this.BookingCruisePassenger = new HashSet<BookingCruisePassenger>();
        }
    
        public int Id { get; set; }
        public int IdTypeCruise { get; set; }
        public int IdShip { get; set; }
        public int IdDestination { get; set; }
        public string Code { get; set; }
        public System.DateTime SailingDate { get; set; }
        public int SailingLengthDays { get; set; }
        public bool IsExtract { get; set; }
        public string Extract { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Editor { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCruisePassenger> BookingCruisePassenger { get; set; }
        public virtual Lov LovDestination { get; set; }
        public virtual Lov LovShip { get; set; }
        public virtual Lov LovTypeCruise { get; set; }
    }
}
