//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string User { get; set; }
        public System.DateTime Date { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Action { get; set; }
        public Nullable<int> Booking { get; set; }
        public string Details { get; set; }
    }
}
