//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger()
        {
            this.Document = new HashSet<Document>();
            this.Information = new HashSet<Information>();
            this.BookingActivity = new HashSet<BookingActivity>();
            this.BookingCruisePassenger = new HashSet<BookingCruisePassenger>();
        }
    
        public int Id { get; set; }
        public int IdAdvice { get; set; }
        public int IdStatus { get; set; }
        public int IdTitle { get; set; }
        public Nullable<int> Number { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool IsEmailUpdated { get; set; }
        public Nullable<bool> IsEmailValid { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public int SentCount { get; set; }
        public bool IsExtract { get; set; }
        public string Doctor { get; set; }
        public Nullable<System.DateTime> TreatmentDate { get; set; }
        public string Review { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Editor { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public Nullable<bool> AutoAttachment { get; set; }
        public string UsualName { get; set; }
        public string Token { get; set; }
        public bool IsDownloaded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Information> Information { get; set; }
        public virtual Lov LovAdvice { get; set; }
        public virtual Lov LovStatus { get; set; }
        public virtual Lov LovTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingActivity> BookingActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCruisePassenger> BookingCruisePassenger { get; set; }
    }
}
