//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAgencyAccessRight
    {
        public int Id { get; set; }
        public int IdAgency { get; set; }
        public string AgencyName { get; set; }
        public string CruiseCode { get; set; }
        public string GroupName { get; set; }
        public int BookingNumber { get; set; }
    }
}
