//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCriteria
    {
        public int Id { get; set; }
        public int Order { get; set; }
        public string CruiseType { get; set; }
        public string Destination { get; set; }
        public string Ship { get; set; }
        public Nullable<int> Length { get; set; }
        public string Cruise { get; set; }
        public string Activity { get; set; }
        public string Survey { get; set; }
        public System.DateTime ModificationDate { get; set; }
    }
}
