//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCruiseShore
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> IdTypeCruise { get; set; }
        public string TypeCruise { get; set; }
        public System.DateTime DateDeparture { get; set; }
        public Nullable<int> IdDestination { get; set; }
        public string Destination { get; set; }
        public Nullable<int> IdShip { get; set; }
        public string Ship { get; set; }
        public string Agency { get; set; }
        public bool IsExtract { get; set; }
    }
}
