//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCruiseBoard
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime SailingDate { get; set; }
        public int NbPassenger { get; set; }
        public int NbQMAvailable { get; set; }
        public int NbQMDone { get; set; }
        public int SailingLengthDays { get; set; }
        public int IdShip { get; set; }
        public int NbQMNotAvailable { get; set; }
        public int NbQMReceive { get; set; }
        public int NbQMValidate { get; set; }
        public int NbQMWaiting { get; set; }
        public int NbQMRefused { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> IdShipAssigned { get; set; }
    }
}
