//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPassengerShore
    {
        public int Id { get; set; }
        public string Civility { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public bool EmailUpdated { get; set; }
        public Nullable<bool> ValidEmail { get; set; }
        public string PhoneNumber { get; set; }
        public int IdStatus { get; set; }
        public string QMStatus { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public int NbSent { get; set; }
        public int IdAdvice { get; set; }
        public string Advice { get; set; }
        public string Doctor { get; set; }
        public Nullable<System.DateTime> TreatmentDate { get; set; }
        public bool IsEnabled { get; set; }
        public string Review { get; set; }
        public bool IsExtract { get; set; }
        public Nullable<bool> AutoAttachment { get; set; }
        public string UsualName { get; set; }
        public bool IsDownloaded { get; set; }
        public string BookingAgency { get; set; }
        public int BookingNumber { get; set; }
        public string BookingOffice { get; set; }
        public int BookingIdOffice { get; set; }
        public int IdBooking { get; set; }
        public string GroupName { get; set; }
        public bool IsGroup { get; set; }
        public int IdCruise { get; set; }
        public string CruiseCode { get; set; }
        public string DoctorId { get; set; }
    }
}
