//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPassengerBoard
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string UsualName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public int IdAdvice { get; set; }
        public string Review { get; set; }
        public int IdStatus { get; set; }
        public bool IsExtract { get; set; }
        public string Doctor { get; set; }
        public int IdCruise { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public bool IsDownloaded { get; set; }
    }
}
