//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponant.Medical.Data.Shore
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSurvey
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Languages { get; set; }
        public Nullable<int> NbIndividualSurveyMail { get; set; }
        public Nullable<int> NbGroupSurveyMail { get; set; }
        public bool MedicalAdvice { get; set; }
        public Nullable<int> NbIndividualSurveys { get; set; }
        public Nullable<int> NbGroupSurveys { get; set; }
    }
}
